### ISSUE TITLE
Filter issues based on labels

### ISSUE THREAD

**Issue by jahtomini** [calcom/synclinear.com#105]
I think it would be a nice QoL improvement to be able to filter in the UI which repository a set of issues are synced to based on their labels, e.g every label tagged `repo: go-backend` would go to the repository `go-backend`. 

I'd like to work on this.

**Comment by tedspare** [comment]
Hey @jahtomini - great idea! This is [very in-demand](https://github.com/calcom/synclinear.com/issues/15#issuecomment-1289045972). All yours, and please let me know if/when you need code review.
