### ISSUE TITLE
images disappear in github after syncing

### ISSUE THREAD

**Issue by PeerRich** [calcom/synclinear.com#106]
all uploaded images on github will disappear on github after syncinc with linear because right now we reupload them to linear which link is not accessible on github.

the file upload has to stay on github

**Comment by hariombalhara** [comment]
@PeerRich is there a workaround for this at the moment? I can't seem to find a way to add a screenshot to github issues.

**Comment by PeerRich** [comment]
like here: https://github.com/calcom/cal.com/issues/9838

**Comment by PeerRich** [comment]
this is by far the most important bug to fix right now

**Comment by tedspare** [comment]
It looks like both GitHub and Linear have stopped rendering each other's images. Looking into uploading images to a third-party storage provider.

**Comment by tedspare** [comment]
Added source links to images as a backstop solution. Working on a permanent solution.

![image](https://github.com/calcom/synclinear.com/assets/36117635/ffcc6680-c667-4f6e-b9c0-f32c0eacf502)

**Comment by tedspare** [comment]
Added a fix in c8de51803d572dbd0313d73834c46cfe7c0bea40 to preserve images uploaded via GitHub.

Images uploaded via Linear remain auth-walled (thus broken on GH) but a Linear eng is helping us to get it sorted 🙌
