### ISSUE TITLE
Nothing syncing between GitHub or Linear

### ISSUE THREAD

**Issue by Brendonovich** [calcom/synclinear.com#107]
Been trying to get this set up for Spacedrive, but we have no indication that anything is syncing.
We've tried creating a `linear` tag in GitHub and a `Public` tag in Linear, and assigned them to multiple issues, and after hours they're still not synced.
Could this be because we previously had the old version of synclinear hooked up?

<img width="961" alt="image" src="https://github.com/calcom/synclinear.com/assets/14191578/2e155c31-db1e-48be-97e8-8f9d6a074248">

**Comment by dolevelb** [comment]
Same here. Sync used to work a week ago, but now I've tried for multiple repos and it doesn't seem to work. Webhooks are active and apps are authorized on both sides (GitHub, Linear).

**Comment by tedspare** [comment]
Thanks @Brendonovich - sorry it's not working. I have a few questions. Can you see the active webhook under [Linear settings > API > webhooks](https://linear.app/settings/api) and GitHub repo > settings > webhooks? If so, can you see Recent Deliveries under the GH webhook? What are the responses? Thanks in advance

**Comment by Brendonovich** [comment]
@tedspare Yep, both Linear and GitHub have active webhooks:
<img width="282" alt="image" src="https://github.com/calcom/synclinear.com/assets/14191578/3c6acbd9-2b28-415d-bb06-f5786e8eebbc">
<img width="370" alt="image" src="https://github.com/calcom/synclinear.com/assets/14191578/34484f88-ada0-4620-96cd-57f0d8b043ec">
Strangely, all `issue_comment.created` events are getting 404 responses:
<img width="592" alt="image" src="https://github.com/calcom/synclinear.com/assets/14191578/a9ee48a6-4a0c-4b7f-b8fe-eae2a0c7dcba">

**Comment by utkubakir** [comment]
^^ In addition to this, we get 500 on `issues.opened`. I am guessing this is what's causing others to fail.

`{"success":false,"message":"Entity not found - labelIds contained an entry that could not be found."}`

**Comment by tedspare** [comment]
Thanks @Brendonovich and @utkubakir - will work on this under #84

**Comment by tedspare** [comment]
Thanks @Brendonovich and @utkubakir - will work on this under #84
