### ISSUE TITLE
Repository dropdown order

### ISSUE THREAD

**Issue by marwie** [calcom/synclinear.com#108]
Hi, currently its very annoying/hard to select a repository if you have a lot

The order seems random and there's no way to search. I have > 200 repositories and can not find the one I'm looking for

I might try to make a improvement to the code but I'm not very familiar with react anymore

![image](https://github.com/calcom/synclinear.com/assets/5083203/8a0a43fd-1610-41e1-b738-643a73fa4e71)

**Comment by tedspare** [comment]
Thanks @marwie. Huge if you take this on 💪 

[ShadCN's Select component](https://ui.shadcn.com/docs/components/select) offers some nice examples with search.

The GitHub API allows up to 100 results at a time (currently sorted by last-updated), so the hard part imo will be fetching + collecting >100 results.

Happy to review code when ready
