### ISSUE TITLE
Adding "linear" tag doesn't sync issue from GitHub to Linear

### ISSUE THREAD

**Issue by jonathimer** [calcom/synclinear.com#118]
Expected behavior: When adding the `linear` tag, GitHub issues that are not in Linear yet, should be synced to Linear.

This currently doesn't work for. I also tried to connect everything via https://synclinear.com/.

See example: https://github.com/CrowdDotDev/crowd.dev/issues/1169

**Comment by tedspare** [comment]
Thanks @jonathimer - could you try signing into GitHub on SyncLinear.com, removing the sync (if visible), then re-syncing? Let me know if this doesn't fix it.

**Comment by jonathimer** [comment]
I just did the re-sync and also removed/added the tag again. It's still not working.

**Comment by tedspare** [comment]
Thanks, Jon. It seems there's an issue with GH label events affecting a few areas. Looking into it.

**Comment by tedspare** [comment]
Hey again @jonathimer. We made some updates to the GH label listener - is the issue still happening?

**Comment by jonathimer** [comment]
Thanks for getting back. Unfortunately, its still not solved for me.

Adding the "linear" tag to any issue doesn't do anything. I also tried to re-connect the whole integration again.

**Comment by kautukkundan** [comment]
For us it doesn't sync when someone else (one who hasn't deployed the webhook) from the contributor list opens an issue and tags it with "linear" is there any workaround for that?

**Comment by tedspare** [comment]
@kautukkundan unfortunately not, intentionally. This is to prevent bad actors from affecting a private Linear team through this tool.

**Comment by nikitnikoks** [comment]
@tedspare was the issue resolved? It doesn't work for me either. I use different emails for Linear and Github, but I authorized both apps, so the webhook should be added.

**Comment by Jstein77** [comment]
@tedspare I'm hitting the same thing! Thanks for looking into this, this project is awesome.

**Comment by tedspare** [comment]
Not yet @nikitnikoks and thanks @Jstein77! Looking into it right now. A few others have reported this offline so I think the webhook structure changed.

**Comment by Jstein77** [comment]
@tedspare no dice. I tried redeploying the webhook, and tagging and issue in github with `linear` but did not see it sync to my linear project.

**Comment by haroldao** [comment]
Same issue here 👀

**Comment by tedspare** [comment]
Sorry about that! In your repo > Settings > Webhooks > SyncLinear.com > Recent Deliveries > 1 > Response, do you see an error message related to the GitHub token?

**Comment by haroldao** [comment]
> 

Nothing

**Comment by joanagmaia** [comment]
> Sorry about that! In your repo > Settings > Webhooks > SyncLinear.com > Recent Deliveries > 1 > Response, do you see an error message related to the GitHub token?

Hey @tedspare I get the same issue, and in Webhooks log I get this message:
`{"success":false,"message":"GitHub webhook secret doesn't match up."}`
Error code: 403

**Comment by tedspare** [comment]
Thanks @joanagmaia. It seems webhook secrets are expiring and not refreshing (I see no docs on this). Thinking of a secure way to refresh them when this error comes up. In the meantime, feel free to get in touch and we can roll it manually.

![image](https://github.com/calcom/synclinear.com/assets/36117635/43ccf341-f4f6-439e-a117-b120c0a6661f)

**Comment by joanagmaia** [comment]
@tedspare at the moment, we are getting this error for all deliveries
And the sync is not working for any of us, neither from github or to github

What would be the fix for this to update the secret as you have on your screen?
![Screenshot 2023-09-12 at 17 05 27](https://github.com/calcom/synclinear.com/assets/20134207/8f98f1db-9e04-442e-a21a-b847bc939f07)

**Comment by tedspare** [comment]
Yep, reach out to me and we'll update it in the DB! (Temp solution)

**Comment by ArctypeZach** [comment]
Trying to evaluate this tool as a solution for our org and running into the same issue— Linear -> GH works just fine, but tagging GH issues fails to sync them.  Re-syncing does not appear to have any effect

**Comment by tedspare** [comment]
Closing as resolved, thanks @joanagmaia @ArctypeZach!

**Comment by Jstein77** [comment]
Hey @tedspare i'm seeing the same error message 
`
{"success": false,"message":"GitHub webhook secret doesn't match up."}`

Can I get your help updating the secret?
