### ISSUE TITLE
Sync stopped working completely

### ISSUE THREAD

**Issue by jonathimer** [calcom/synclinear.com#121]
Our sync stopped working completely:

- When tagging Linear issues with "public" they don't get synced to GitHub. 
- When tagging GitHub issues with "linear" they don't get synced to Linear. As mentioned in [this issue](https://github.com/calcom/synclinear.com/issues/118) already.

I tried to re-connect it several times. My co-founder connected another Linear team (but same workspace) to another GitHub repo recently. Could that be the root cause?

<img width="2547" alt="Bildschirmfoto 2023-08-04 um 12 38 40" src="https://github.com/calcom/synclinear.com/assets/41432658/d1352951-5c58-49c4-a430-3670fa160cf2">

**Comment by tedspare** [comment]
Sorry to hear this, @jonathimer. Is your co-founder's sync working?
