### ISSUE TITLE
Org repos do not show in UI

### ISSUE THREAD

**Issue by nikitavoloboev** [calcom/synclinear.com#127]
I want to connect it to this repo: https://github.com/learn-anything/learn-anything.xyz

But it's part of organisation. When I try to sync to github repo, it does not show me any organisation repos.

**Comment by nikitavoloboev** [comment]
Perhaps I have to manually have to add permission for organisation? I could not find it in the UI how to do it.

Would really appreciate getting this resolved as I want to use your tool for organisation level issues. It should work in theory as I assume https://github.com/calcom/cal.com uses it and its an org. or even https://github.com/calcom/synclinear.com

**Comment by chrisainerd** [comment]
This is what I want!
Is there anybody to resolve it?

**Comment by nikitavoloboev** [comment]
Most likely it's not supported yet. Have to fork of and try add it ourselves it seems.

**Comment by tedspare** [comment]
Hey @nikitavoloboev @chrisainerd, sorry for the late reply.

As you noted, there are orgs using the tool so the issue is upstream somewhere preventing GH from listing that org's repos to you. If you're an admin of the org, do [these steps](https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization) work?

Profile photo > Your organizations > <your org> > Third-party Access > OAuth Application policy > SyncLinear > Edit > Grant Access

Let me know if this doesn't work!

**Comment by tedspare** [comment]
@nikitavoloboev have you had a chance to revisit this?

**Comment by nikitavoloboev** [comment]
@tedspare 

Yes I still can't connect my org repo :(

Here is video of me trying:

https://github.com/calcom/synclinear.com/assets/6391776/dc0367e1-4222-4e86-9fbd-2653d3211d6d

Let me know how I can resolve it, would really appreciate it. ♥️

**Comment by tedspare** [comment]
Thanks for sharing @nikitavoloboev! Were you able to follow the org settings steps I shared [here](https://github.com/calcom/synclinear.com/issues/127#issuecomment-1699710313)?

**Comment by nikitavoloboev** [comment]
> Profile photo > Your organizations > > Third-party Access > OAuth Application policy > SyncLinear (if it shows) > Edit > Grant Access

tried doing this, saw this:

<img width="1343" alt="image" src="https://github.com/calcom/synclinear.com/assets/6391776/542ae401-94d7-45fb-831d-5888650046f5">

@tedspare 

not sure what i should try now

**Comment by nikitavoloboev** [comment]
> org settings > Member privileges > Integration access requests

I have this set there

<img width="775" alt="image" src="https://github.com/calcom/synclinear.com/assets/6391776/859cc701-8d98-4a7f-8792-957e2708ca34">

**Comment by tedspare** [comment]
Thanks for trying that, @nikitavoloboev. In the [GitHub Explorer](https://docs.github.com/en/graphql/overview/explorer), do you see those Learn-Anything repos if you run this query?

```gql
query { 
  viewer { 
    repositories(first: 100) {
      totalCount
      nodes {
        nameWithOwner
      }
    }
  }
}
```

**Comment by nikitavoloboev** [comment]
Just tried it and I don't see the repos there.

**Comment by nikitavoloboev** [comment]
Is there anything I can do to add the org to the scope?

**Comment by nikitavoloboev** [comment]
@tedspare anything I can try to make it work? 🙏

**Comment by tedspare** [comment]
Woops, thanks for the follow-up @nikitavoloboev. Seeing that the org repos don't show in GH Explorer tells me there's an org setting preventing a member (or, at least, your) account from accessing repos.

Two more ideas:
- In Org > People > [your account] > Role, do you see "Owner"?
- In personal Settings > Applications > Authorized OAuth Apps > SyncLinear.com, can you grant access?

<img width="1292" alt="image" src="https://github.com/calcom/synclinear.com/assets/36117635/1b30b5d6-6900-4495-9e87-03a004fa7b8c">

![image](https://github.com/calcom/synclinear.com/assets/36117635/f6dfeced-23bb-44c0-86d8-db6f010dc2f6)

**Comment by nikitavoloboev** [comment]
> In personal Settings > Applications > Authorized OAuth Apps > SyncLinear.com, can you grant access?

This was the missing piece.

![CleanShot 2023-09-13 at 07 28 51@2x](https://github.com/calcom/synclinear.com/assets/6391776/d8c16e6c-eda1-48aa-afa5-6f87bf5abae6)

Had to tick an org here. Now it works. 🎊 

Thanks a lot. And thanks for building this great tool.
