### ISSUE TITLE
Railway deploy fails due to defaulting to Dockerfile

### ISSUE THREAD

**Issue by joanreyero** [calcom/synclinear.com#129]
The 1-click deploy on Railway is currently not working. It builds fine, but at the past step I get an error:
```
The start command is invalid.
Start command: `pnpm start`
```
<img width="381" alt="Screenshot 2023-08-23 at 12 34 16" src="https://github.com/calcom/synclinear.com/assets/37874460/05ea9f7b-97c3-4078-b97a-f5dd03242fe6">

**Comment by vmatsiiako** [comment]
I'm experiencing the same error. Is there any workaround?

**Comment by tedspare** [comment]
Thanks. The problematic script was in the Procfile, so I changed it to use npm in d5dfef7d1684048712666d73b199e85004cc93a7.

If you try again, does it still fail?

**Comment by vmatsiiako** [comment]
Hmmm, it still says pnpm. Any ideas why? 

<img width="1072" alt="Screenshot 2023-08-31 at 20 48 21" src="https://github.com/calcom/synclinear.com/assets/78047717/1ad31305-6625-4698-8630-320fe865597a">

**Comment by tedspare** [comment]
Weird. I've redeployed the Railway template and published it [here](https://railway.app/template/L__0PR). Does it show the same there?

**Comment by tedspare** [comment]
@joanreyero please feel free to give it another try too

**Comment by vmatsiiako** [comment]
Thank you for your help! I'm now running into a different kind of error. Could it be that this is because of wrong environment variables? 

<img width="1075" alt="Screenshot 2023-09-05 at 20 36 31" src="https://github.com/calcom/synclinear.com/assets/78047717/a4b94ee4-2a35-4713-8fdb-070ed6f6f939">

**Comment by joanreyero** [comment]
Thanks! Same issue.

**Comment by vmatsiiako** [comment]
If that's possible, I'm happy to jump on a quick call to see if maybe I'm doing something wrong.

**Comment by tedspare** [comment]
@vmatsiiako always blame the machine; never yourself.

Taking a look into the `/health-check` endpoint! In the Railway UI, can you access your Postgres instance? If so, is it populated with tables? Thanks again.

**Comment by vmatsiiako** [comment]
1. I can access the Postgres instance, but there are no tables in it
<img width="2001" alt="Screenshot 2023-09-07 at 10 47 39" src="https://github.com/calcom/synclinear.com/assets/78047717/b52909f4-3b82-4f9c-a8ae-cf8a1017aa3b">
2. I can see the git repository, so yes, the next.js app is there
3. yes, it still persists

**Comment by tedspare** [comment]
Was able to replicate this finally. Looks like Railway is using the Dockerfile (written for DigitalOcean) [by default](https://docs.railway.app/deploy/dockerfiles) instead of the Procfile.

Got any experience with Dockerfiles?

<img width="848" alt="image" src="https://github.com/calcom/synclinear.com/assets/36117635/17e6ba7f-7f05-4d4a-8675-263dda14e901">

**Comment by tedspare** [comment]
Added a note to README. This seems to be the way:

![image](https://github.com/calcom/synclinear.com/assets/36117635/39460426-3d9f-4262-907b-bf21673d57bf)

**Comment by vmatsiiako** [comment]
Thank you so much! It deploys now. I'm running into a different issue though. Do you maybe now what is happening? 

<img width="1389" alt="Screenshot 2023-09-07 at 11 57 19" src="https://github.com/calcom/synclinear.com/assets/78047717/9b180b73-1563-47ec-9a3a-7cc9e7e4cf82">

**Comment by vmatsiiako** [comment]
Where in Railway am I supposed to run these two commands? 

<img width="964" alt="Screenshot 2023-09-07 at 12 16 23" src="https://github.com/calcom/synclinear.com/assets/78047717/56a8186c-d205-494c-8b48-0f3039c9599d">
