### ISSUE TITLE
Self hosted doens't seem to work

### ISSUE THREAD

**Issue by githubdoramon** [calcom/synclinear.com#130]
I've deployed a self-hosted version, and deployed the webhooks, but it doesn't seem to work (no issues are created or synced).

<img width="1072" alt="image" src="https://github.com/calcom/synclinear.com/assets/8230135/979d09a8-ccf9-4090-9315-e79ccc2b1283">

What is the right way to start debugging this? How to check what hooks are actually deployed? Or which logs/tables to check for errors?

**Comment by yorik** [comment]
I think there is some wrong with user and sync: tables `users`, `syncs` and `synced_issues` are empty. (Tables `linear_teams` and `github_repos` have some data which makes sense.)

Webhooks are installed in both Github and Linear, but webhook in github repo always gets 404 error from synclinear/api:
`{"success":false,"message":"Could not find sync for matter-labs/era-test-node"}`

Also when I try to add a team from Linear I got error popup:
`    "error": "Failed to save sync with error: \nInvalid `prisma.sync.upsert()` invocation:\n\n\nError occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: Some(Error), code: SqlState(E42P10), message: \"there is no unique or exclusion constraint matching the ON CONFLICT specification\", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some(\"plancat.c\"), line: Some(860), routine: Some(\"infer_arbiter_indexes\") }) }), transient: false })"
` 

So looks like database schema has some conflicts.

**Comment by yorik** [comment]
Looks like adding unique index like following helps:
````
create unique index concurrently ix_syncs_t1 on "public"."syncs" ("githubUserId","linearUserId","githubRepoId","linearTeamId");
```

But it should be done automatically by prism: https://github.com/calcom/synclinear.com/blame/7cba738cf777cf41616eb1701a621a1f9a0a98b9/prisma/schema.prisma#L81C71-L81C71

I wonder why it's missing in migrations...
