### ISSUE TITLE
Extra tags are ignored when adding multiple at the same time

### ISSUE THREAD

**Issue by Xiexe** [calcom/synclinear.com#133]
When adding the linear tag manually to a GitHub issue, if you also add another tag at the same time, the extra tag(s) does not get synced over to linear.

**Comment by tedspare** [comment]
Thanks @Xiexe. This seems like an oversight on our part. Open to PRs.

**Comment by rockingrohit9639** [comment]
@tedspare can I work on this issue ?

**Comment by tedspare** [comment]
@rockingrohit9639 yessir! Ping me whenever you'd like to pair-program (onboarding, code review, etc)

**Comment by rockingrohit9639** [comment]
@tedspare Ok thanks. Btw, do you have discord or something to connect with you for seamless communication?

**Comment by tedspare** [comment]
@rockingrohit9639 check out the [Cal.com Discord](https://discord.gg/FJXrhxa3)!

**Comment by rockingrohit9639** [comment]
@tedspare I cannot find you. I have sent a text in #general channel, can you please reply there so that we can discuss further.

**Comment by tedspare** [comment]
Closed by @rockingrohit9639 in #136  🎉
