### ISSUE TITLE
Sync linear with github issue when label is added

### ISSUE THREAD

**Issue by Wyatt-SG** [calcom/synclinear.com#134]
Currently Github issues are created/synced when a new linear issue is created with the "Public" tag. 

I would like the ability to add the "Public" label to a linear issue after creation and have it then sync and create a Github issue.

**Comment by tedspare** [comment]
Hi @Wyatt-SG, thanks for raising this. This is the intended behaviour (ability to add the `Public` label after creation). Is it not working?

**Comment by xiaofei-du** [comment]
Hello @tedspare, we're encountering a related issue.

We initiated a ticket in Linear "INS-1250" and subsequently added the `Public` label to it.

**Expected Outcome**
Our expectation was for a new GitHub issue to be generated, connected to this Linear ticket "INS-1250".

**Actual Outcome**
However, what occurred was the creation of a new GitHub issue on GitHub, which, in turn, triggered the generation of a new Linear ticket, "INS-2020". This new GitHub issue became linked to the Linear ticket "INS-2020". You can view this at https://github.com/instill-ai/community/issues/368.

We are uncertain if removing our syncs from your database would resolve this issue. Any insights or assistance would be greatly appreciated. Thank you!

**Comment by vincelwt** [comment]
@tedspare When you say this is intended behavior you mean it should already do this? (when adding a Public label to a Linear ticket after creation, create a GitHub issue) or it shouldn't?  (Currently seems like it doesn't) 

Thanks!
