### ISSUE TITLE
Request to reduce permission set

### ISSUE THREAD

**Issue by samlaf** [calcom/synclinear.com#146]
When connecting to github on https://synclinear.com/, it requests permissions to all of our org's private repos, including deploy keys and everything.

<img width="521" alt="image" src="https://github.com/calcom/synclinear.com/assets/9342524/bc4abe27-383b-431e-815b-ac38c77bc57e">

This seems very unreasonable, and makes this app unusable for us, which is very unfortunate. linear-sync have solved this [very same issue](https://github.com/jtormey/linear-sync/issues/3) by using fine-grained permissions. Is there a way for synclinear to do the same?

**Comment by tedspare** [comment]
Thanks for raising this. Maybe a GitHub App refactor could solve this, otherwise GitHub's `repo` scope doesn't distinguish read from write permission. See #47.
