### ISSUE TITLE
Issues from other team members and users are not synched

### ISSUE THREAD

**Issue by AlbertMitjans** [calcom/synclinear.com#147]
I am an admin of an open source Python library (https://github.com/qilimanjaro-tech/qililab).

I recently linked Linear with this repo, but I found out that only the Issues I create are synched with Linear. Issues created by my team members and/or external users are not synched...

**Comment by tedspare** [comment]
Hey @AlbertMitjans, each Linear team member who would like their issues to sync will need to sign up! The app acts on a user's behalf so consent is necessary. Please let me know if there are any issues with that.
