### ISSUE TITLE
GitHub issues.opened and issues.labeled webhook always failed due to SQL error

### ISSUE THREAD

**Issue by kentwelcome** [calcom/synclinear.com#158]
When configuring the SyncLinear on my GitHub repo, I found the `issues.opened` and `issues.labeled` always got response 500 from `synclinear.com/api` in my GitHub webhook history log.

Seems the schema of the GitHub Issue ID in SyncLinear DB is INT4 (32bits). However, the GitHub Issue ID was already bigger than 32 bits. 

Please reference the following response payload by `POST https://synclinear.com/api`

```JSON
{
  "success": false,
  "message": "\nInvalid `prisma.syncedIssue.create()` invocation:\n\n\nError occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(3), cause: Some(Error { kind: ConversionError(\"Unable to fit integer value '2160748434' into an INT4 (32-bit signed integer).\"), original_code: None, original_message: None }) }), transient: false })"
}
```

**Comment by tedspare** [comment]
Closed by #159
