### ISSUE TITLE
Adding a comment with image in Github doesn't show the image in Linear

### ISSUE THREAD

**Issue by hariombalhara** [calcom/synclinear.com#19]
Adding a new comment in Github with an image doesn't show the image in Linear
The image's markup is there but it's not parsed it seems
<img width="845" alt="Screenshot 2022-10-21 at 11 02 28 AM" src="https://user-images.githubusercontent.com/1780212/197120088-5b22fd12-8014-47d1-a363-f05fec01567f.png">

**Comment by tedspare** [comment]
Thanks! Should be fixed by 644000c653a236df3ba358039b81a31cc7d609c2. Please feel free to reopen this if not.

**Comment by kautukkundan** [comment]
Receiving this error after sync replaces the img url from github to Linear
`NoSuchKeyThe specified key does not exist.`
