### ISSUE TITLE
Issue moved back to 'in progress' after PR is created

### ISSUE THREAD

**Issue by JeroenReumkens** [calcom/synclinear.com#21]
When I manually update an issue in linear to 'in review', create a PR afterwards in Github, the issue status in linear goes back to 'in progress'.

**Comment by tedspare** [comment]
Thanks @JeroenReumkens. Do you have the Linear [GitHub integration](https://linear.app/integrations/github) installed? If so, it can be [re-configured](https://linear.app/settings/integrations/github) to move PR-linked issues to 'in review'. Hope this helps!

**Comment by tedspare** [comment]
Closing as out of scope, but please let me know if you think we should re-open it
