### ISSUE TITLE
GitHub webhook deployment not working.

### ISSUE THREAD

**Issue by Codeize** [calcom/synclinear.com#25]
Hey there team, thanks for this project, seems very cool!

An issue I've faced while trying to get setup is that the `Deploy Webhook` button seems to be already deployed when I go to deploy the GitHub webhook on my repo, but when I look in the Webhook settings of the GitHub repo there is no SyncLinear webhook, there is however a Discord one I use to relay events, it may be possible that it's conflicting with the setup?

I'm not sure if this is something I've broken accidentally, but I've followed the steps that were detailed so not really sure where I went astray, if it was me.

Thanks!

**Comment by tedspare** [comment]
Thanks for the kind words, @Codeize!

The `Deploy Webhook` button actually checks against our DB for an existing repo (to avoid duplicate webhooks). I'll see if we can improve this by checking the GitHub API for the actual webhook.

In the meantime, is it possible someone on your team removed the webhook?

I'd be happy to remove your repo from the DB for a fresh start. If that sounds good, what's your repo called?

**Comment by Codeize** [comment]
> Thanks for the kind words, @Codeize!
> 
> The `Deploy Webhook` button actually checks against our DB for an existing repo (to avoid duplicate webhooks). I'll see if we can improve this by checking the GitHub API for the actual webhook.
> 
> In the meantime, is it possible someone on your team removed the webhook?
> 
> I'd be happy to remove your repo from the DB for a fresh start. If that sounds good, what's your repo called?

Hmmm, maybe when testing I could have messed something up, sorry for the hassle if so.

My repo is called `PizzaPlace/bot`, thanks!
Is there anything else I need to remove or reconfigure to make sure this attempt at setup goes well?

Appreciate your fast response!

**Comment by tedspare** [comment]
Ah ok, this is an edge case - `PizzaPlace/bot` was one of the first repos in the DB, during active dev, so it was missing a webhook secret and I removed it. Not your fault!

What's your Linear team name (feel free to DM me on Twitter or edit this afterwards)? Otherwise, should be ready to try re-syncing from scratch.

Data dashboard is on the roadmap!

**Comment by Codeize** [comment]
My Linear team name was changed since I first tried to setup SyncLinear, it was called Engineering I believe, now it's called `Bot Engineering`, the workspace is called PizzaPlace. Is this what you're after?

I also tried to re-sync and it still hasn't created the webhook GitHub-side.

**Comment by Codeize** [comment]
This was resolved after quite some back and forth between myself and Ted, essentially Ted had to delete my DB data and I had to delete and recreate a few webhooks.

Really weird issue that still has no real clear explanation, but thanks for the help Ted, excited to see where this project can go :)
