### ISSUE TITLE
does not add a webhook to github

### ISSUE THREAD

**Issue by abrahamcalsin** [calcom/synclinear.com#27]
It doesn't add a webhook to my github repository when I select my project repo to sync with _**linear.app**_, it loads, but when I go back to github I don't see a webhook added.

## synclinear.com

![image](https://user-images.githubusercontent.com/77748010/200990776-896ec452-f162-4b76-bb41-b26e4ec8c872.png)

## GitHub settings

![image](https://user-images.githubusercontent.com/77748010/200991127-f6170f3d-9d72-4200-9950-766d39a95a9a.png)

---

PS: The first one did add a webhook, but then I deleted it and re-synced my repo, but this time it no longer added a webhook.

**Comment by tedspare** [comment]
Thanks for raising this @abrahamcalsin. To clarify, the first one added a webhook, meaning Linear or _GitHub the first time_?

Also, do you know if there was an error in the console? No worries if not

Will try to replicate this and push a fix

**Comment by abrahamcalsin** [comment]
> Thanks for raising this bug @abrahamcalsin
> 
> To clarify, when you say "the first one added a webhook", do you mean Linear or GitHub had the webhook?
> 
> Also, did you manually delete the GH webhook by chance?
> 
> These will help to troubleshoot then push a fix!

Well, the first time, it added me a webhook in github.
More on linear added me as an Authorized Application just that.

Yes, in github the webhook I deleted it manually, and when I try to sync again it doesn't recognize that I deleted it and that's why it doesn't add me a new webhook.

**Comment by tedspare** [comment]
Thanks for clarifying, @abrahamcalsin. I'll look into adding a guardrail for manually-deleted webhooks.

In the meantime, to fix your sync, feel free to manually add the webhook back:
- Endpoint: `https://synclinear.com/api`
- Content type: `application/json`
- SSL verification: `Enable`
- Events: `Let me select individual events` -> `issues`, `issue comments`, `labels`

Please let me know if that doesn't work!

**Comment by abrahamcalsin** [comment]
> Thanks for clarifying, @abrahamcalsin. I'll look into adding a guardrail for manually-deleted webhooks.
> 
> In the meantime, to fix your sync, feel free to manually add the webhook back:
> 
> * Endpoint: `https://synclinear.com/api`
> * Content type: `application/json`
> * SSL verification: `Enable`
> * Events: `Let me select individual events` -> `issues`, `issue comments`, `labels`
> 
> Please let me know if that doesn't work!

Well I tried to manually add a webhook and I get a 500 error, so it doesn't work.

Could it be that I am missing the secret?

**Comment by yang-han** [comment]
I met exactly the same issue here 🙌 Thanks for the authors looking into it

**Comment by blockmia** [comment]
@tedspare 
I had the same problem.
Webhooks were added when first synchronizing.   They will not be added when manually removed and then synchronized again.
Secret is missing on GitHub if I fill it in manually, so how do you get secret or can you automatically add it again when synchronizing after detecting the deleted webhooks?
