### ISSUE TITLE
Nothing is syncing, how do I debug?

### ISSUE THREAD

**Issue by nikolausWest** [calcom/synclinear.com#30]
I've set up syncing between a Linear project and a Github repo on https://synclinear.com/. It says it's successful but I'm not seeing any Github issues show up after i add the label "Public" to issues in Linear.

How do I go about debugging this?

**Comment by tedspare** [comment]
Hey @nikolausWest. I'm seeing that you're in the DB but your sync is not. I also see
- a sync failed to save at 3:33pm EST yesterday
- someone deleted a sync at 3:56pm EST yesterday

Assuming the sync failure was for your project, it looks like a new bug and I'll try to replicate it.

In the meantime, could you try syncing again? Thanks for bearing with me.

**Comment by nikolausWest** [comment]
Sorry, missed your update. We ended up deciding to more away from Linear to just use Github issues and avoid the syncing all together.
