### ISSUE TITLE
Issues created with "linear" label open 2 tickets

### ISSUE THREAD

**Issue by tedspare** [calcom/synclinear.com#31]
See [Cal #5699](https://github.com/calcom/cal.com/issues/5669)

Opening a GitHub issue in a synced repo with the `linear` label triggers two sequential webhooks: `issue` and `labelled`.

**Comment by enisze** [comment]
still the case

**Comment by tedspare** [comment]
Addressed in docs: either add `linear` label to a community-submitted issue or open it as a team member
