### ISSUE TITLE
Manually removed webhook breaks re-sync

### ISSUE THREAD

**Issue by lingziyb** [calcom/synclinear.com#32]
I had the same problem.
Webhooks were added when first synchronizing.   They will not be added when manually removed and then synchronized again.
Secret is missing on GitHub if I fill it in manually, so how do you get secret or can you automatically add it again when synchronizing after detecting the deleted webhooks?
<img width="580" alt="image" src="https://user-images.githubusercontent.com/102912827/204489955-904fc2f1-bf08-487c-b9a1-a98c578611d0.png">

_Originally posted by @blockmia in https://github.com/calcom/synclinear.com/issues/27#issuecomment-1330325889_

**Comment by tedspare** [comment]
Thanks @lingziyb. The app should check for an existing webhook on GH but it's currently checking against our DB. I'll make that change.

In the meantime, want to have your records reset in the DB for a fresh sync?

**Comment by lingziyb** [comment]
Alright, thank you @tedspare  very much! I want to reset my records now.

Here are two repository here: 
1 https://github.com/metisdac/Metis-DAC-Web
2 https://github.com/lingziyb/hexo-blog

**Comment by geekflyer** [comment]
@lingziyb  can you please also reset:
1. aptos-labs/aptos-core
2. aptos-labs/test-repo

Thanks!

**Comment by tedspare** [comment]
@lingziyb I've removed your two repositories from the DB. Please let me know if you have trouble re-syncing!

**Comment by tedspare** [comment]
@geekflyer I've removed your two repos from the DB. You should now be able to re-sync.

**Comment by blockmia** [comment]
> 

@tedspare The repositories have been synced, but why the comments can not sync to Github and Linear?

**Comment by tedspare** [comment]
@blockmia could you share an example? Were the comments made by someone in your team who has synced on SyncLinear.com?
