### ISSUE TITLE
Feature suggestion: Syncing public github comments

### ISSUE THREAD

**Issue by scopsy** [calcom/synclinear.com#43]
## Why?
It would be amazing to sync public github conversations to be visible inside Linear. Today the comments in linear are a bit weird because they only reflect core team conversations and missing community comments. 

## How? 
Not sure exactly how best to implement but had in mind two ways:
- Using an existing users as a commenter in Linear and add an annotation in the comment that will link to the real commenter github page
- Somehow use the integration account (similar to the one opening the issues in Triage today)

**Comment by scopsy** [comment]
@tedspare would love to hear your thoughts :) (can help with implementation)

**Comment by PeerRich** [comment]
it would need a bot account in linear, yes
