### ISSUE TITLE
sync does not work from linear team -> github

### ISSUE THREAD

**Issue by geekflyer** [calcom/synclinear.com#46]
Hi,

somehow the sync only works in one direction for me at the moment (github -> linear).
When I make changes on github they appear in linear but not vice-versa. I.e. any change (such as a comment, marking an issue with `Public` etc.) on linear does not lead to a change on github.

See below the involved repos:
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/1221897/209026590-9ffef7b4-0eee-4f0a-b0bd-4b3905019af8.png">

The linear webhook appears to be there as well:

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/1221897/209026709-b8be7fd4-79e6-4f4d-8c53-25ad82aac538.png">
<img width="698" alt="image" src="https://user-images.githubusercontent.com/1221897/209026735-a0cf23b9-fc86-4a3e-8bea-1116ab0bb3af.png">

**Comment by geekflyer** [comment]
If it's too difficult to find out what's wrong I'm happy to setup everything from scratch (pending db wipe).

**Comment by tedspare** [comment]
Hey @geekflyer, sorry for the late response. Assuming the Linear>GH sync is still broken for you, could you tell me a bit more? Did it work before it stopped working? Is it possible someone on your team modified the Linear webhook? Thanks.

**Comment by tedspare** [comment]
Closing as stale. Feel free to re-open.
