### ISSUE TITLE
Issues with syncing two repos to the same linear team

### ISSUE THREAD

**Issue by GryphonGroup** [calcom/synclinear.com#48]
I have one linear team, and two github repos that I would like to sync the same linear issues between both repos. Currently, the issues are only syncing between one of the repos that I have integrated. Can anyone else replicate this?

**Comment by tedspare** [comment]
Thanks @GryphonGroup. One-to-many sync (see #10 and #15) isn't yet supported. I should add a note about this in the docs.

Open to PRs! It would involve looping over each synced repo for a given Linear event, eg. [here in the Linear handler](https://github.com/calcom/synclinear.com/blob/main/utils/webhook/linear.handler.ts#L907).

**Comment by GryphonGroup** [comment]
If I get the time/energy I will open a PR! Thanks for the resources
