### ISSUE TITLE
Allow syncing anonymous issues created from GitHub to Linear

### ISSUE THREAD

**Issue by scopsy** [calcom/synclinear.com#52]
## Context
We use linear to triage all our GitHub community issues, and when issues are created by community members they are not synced to linear.

## How?
I was thinking on adding a similar to the anonymous comment functionality, that guest users issues will be created as the "sync app" similar to how the comments work now.

**Comment by PeerRich** [comment]
this works already, just add the issue "linear" to the github ticket and it'll magically appear in linear
![CleanShot 2023-01-14 at 00 37 32@2x](https://user-images.githubusercontent.com/8019099/212437635-4d493af4-6e34-41ec-ac7a-716ae20c0013.jpg)
