### ISSUE TITLE
Sync Linear Estimates?

### ISSUE THREAD

**Issue by PeerRich** [calcom/synclinear.com#55]
Estimates are pretty cool but GitHub has no concept for it.

![CleanShot 2023-01-21 at 20 34 48@2x](https://user-images.githubusercontent.com/8019099/213884118-217b7f7e-6c0e-40cc-9848-b17955194c12.jpg)

should it create labels? XS, M, L, etc.?

there are also different kinds of estimates:

![CleanShot 2023-01-21 at 20 35 52@2x](https://user-images.githubusercontent.com/8019099/213884160-3ba50b5f-e240-4dda-a5ef-88e763b9247a.jpg)

**Comment by tedspare** [comment]
Doable with GH labels eg. `Size L` or `3 points`

Happy to add this if your team would use it?

**Comment by PeerRich** [comment]
yes!! <3
