### ISSUE TITLE
Label "linear" from GitHub does not sync the other labels

### ISSUE THREAD

**Issue by zbeyens** [calcom/synclinear.com#57]
From github, I'm adding "linear" label:
![2023-01-26 at 00 08 27](https://user-images.githubusercontent.com/19695832/214712437-0e2b6fb8-f9da-438a-82bc-37e590522bfd.png)

source: https://github.com/udecode/plate/issues/2025

Linear result:
![2023-01-26 at 00 08 14](https://user-images.githubusercontent.com/19695832/214712405-7191b9e8-76c4-4fb2-8412-02d91c5a3d4c.png)

**Comment by tedspare** [comment]
Thanks @zbeyens. This is a known limitation - we only sync labels from Linear > GH to avoid creating labels in Linear. Hope that's okay!
