### ISSUE TITLE
`Failed to save sync` after Linear team fails to save

### ISSUE THREAD

**Issue by NotPeopling2day** [calcom/synclinear.com#61]
We were wanting to try out your product but running into an error `Failed to save sync.` when attempting to link the Github webhook to our Linear webhook. When looking at the deployed webhook on the Github side, it says  `Last delivery not successful. Invalid HTTP response: 404` error.

Any advice?

**Comment by tedspare** [comment]
Sorry about that, @NotPeopling2day. Do you see the Linear webhook under [settings > API > webhooks](https://linear.app/settings/api)?

If so, could you share the details from the failed _GitHub_ webhook (clicking into the delivery under Recent Deliveries)?

**Comment by NotPeopling2day** [comment]
@tedspare I do see the webhook on Linear, the Github side shows the failure with the 404 and the body is {"success":false,"message":"Could not find issue's corresponding sync."}

**Comment by tedspare** [comment]
Thanks @NotPeopling2day - what's the repo name? Will take a look at the DB

**Comment by JosephTLyons** [comment]
Same thing is happening for me for this repo: https://github.com/zed-industries/community

**Comment by aspiers** [comment]
Same for me.  I just filed #68 since having sourcemaps would greatly help with debugging this.

**Comment by NotPeopling2day** [comment]
@tedspare the repo is https://github.com/ApeWorX/ape

**Comment by JosephTLyons** [comment]
I followed the contributing guideline, but I'm unable to get a dev environment up and running.  If someone on the team could provide the log messages associated with `console.log("Error saving sync:", err.message);`, then maybe we could help troubleshoot the problem.

**Comment by tedspare** [comment]
Thanks @JosephTLyons. This error comes up if we fail to add the `(GH repo, Linear team)` pair to the DB. This could be because a user ID or repo/team ID is missing, or because the combo isn't unique.

 I've added richer error handling in 67760d19aa43a43f30f7fe4127f87baa80f9a31e - please let me know what the new error is and always open to PRs.

**Comment by JosephTLyons** [comment]
@tedspare, here is the newest error:

```
Failed to save sync with error: Foreign key constraint failed on the field: `syncs_linearTeamId_fkey (index)`
```

**Comment by tedspare** [comment]
@JosephTLyons thanks - it looks like the Linear team _failed to save_ first then 😅 .

I've added better observability to that endpoint in ea4bafccf1bfedba75c1b96d402b41c5c6f9d087 - could you give it one more try?

**Comment by JosephTLyons** [comment]
Hmm, I think the error I got was the exact same

```
Failed to save sync with error: Foreign key constraint failed on the field: `syncs_linearTeamId_fkey (index)`
```

**Comment by JosephTLyons** [comment]
Yep.  Tried it 2-3 times and I'm still getting the same error text.  Happy to run this as many times as you need to narrow this down.

**Comment by mnida** [comment]
Dealing with this too!

I tried creating a new team in Linear that had no tickets, and it worked fine on that. However, when using an existing team in linear it is struggling with this error.

**Comment by vsreekanti** [comment]
I was able to track this down to being an issue with the way that Linear states are mapped onto GitHub states [here](https://github.com/calcom/synclinear.com/blob/main/utils/linear.ts#L287-L294). This is hardcoding the state labels to be the default from Linear, and we had customized them in our team, so this operation was failing silently. 

In the short run, I was able to fix this by modifying the code here and self-hosting, but I imagine this will be an issue for other teams as well. I think the best solution would probably be to pull in the workflow states from Linear and then show a UI element asking users to map their canceled/done/todo states manually if they don't use the default labels.

**Comment by tedspare** [comment]
Hey @vsreekanti, a much belated thanks for pinpointing this. Would you be open to sharing your fix? It would benefit quite a few folks!

**Comment by tedspare** [comment]
@vsreekanti thanks for the solution. We've added support for non-default workflow labels in 318ff31d0ec2ab394c9dd298c66e8cecdb9c03f0.

Please let me know if you see the same (or a new) error!

**Comment by JosephTLyons** [comment]
Awesome, its working on our end now! Thank you!

**Comment by tborychowski** [comment]
Thank you so much! It works for me too!

**Comment by vsreekanti** [comment]
Sorry, I just saw this, but it looks like you figured it out. My fix was super hacky — I just replaced them with my own labels and ran a custom instance. 🙂 It looks like your fix is much more generalizable.
