### ISSUE TITLE
HTTP 403 for a github webhook

### ISSUE THREAD

**Issue by andreybavt** [calcom/synclinear.com#65]
I followed the instructions to configure the sync, but on github side I see that the webhook returns a 403 status. Is there an API key that I have to set up?

![image](https://user-images.githubusercontent.com/7889985/219012326-b8d8795d-be7a-40dd-a778-146f58119f3d.png)

As a result, GitHub -> Linear sync doesn't work

Here's a Github webhook response body for the 403 request:

```
{"success":false,"message":"GitHub webhook secret doesn't match up."}
```

To reproduce:

- follow the steps on https://synclinear.com/ to link github and linear
- remove a newly created webhook manually from github repo
- delete synchronisation from https://synclinear.com/
- re-create sync on https://synclinear.com/

**Comment by xiaofei-du** [comment]
Hi @tedspare, I encountered the same issue. Can you please send me the new webhook secret to `xiaofei.du@instill.tech`?
