### ISSUE TITLE
Self hosted github auth problem

### ISSUE THREAD

**Issue by andreybavt** [calcom/synclinear.com#66]
I tried the self hosted version of the app (on railway)

I'm getting the following error when trying to log in with my github account:

![image](https://user-images.githubusercontent.com/7889985/219028665-604e8759-0d87-4d6a-b582-455e107f5397.png)

Here's the github OAuth app settings:

![image](https://user-images.githubusercontent.com/7889985/219029143-cd183f22-37fe-496e-bab9-547c779591b6.png)

**Comment by tedspare** [comment]
Hi @andreybavt - sorry for the late response. If you drop the `/api` endpoint from the `Authorization callback URL`, does it work?

The error comes from `/api`, where — you guessed it — GET requests are dismissed. This tells me the auth step means to be redirecting to the UI, at `/`.

If there was an error in the documentation, could you point me to the exact place?

**Comment by sanderpick** [comment]
He might have followed instructions from here: https://github.com/calcom/synclinear.com/issues/20#issuecomment-1289280892. I ran into same thing, but dropping `/api` does the trick.
