### ISSUE TITLE
sourcemaps missing from hosted deployment

### ISSUE THREAD

**Issue by aspiers** [calcom/synclinear.com#68]
I wanted to try and debug why I was seeing this when using the UI to deploy a GitHub webhook:

![image](https://user-images.githubusercontent.com/100738/219948091-9d93e072-e619-4a95-b4cf-4d2fa43750bc.png)

I looked in the browser console and saw this:

![image](https://user-images.githubusercontent.com/100738/219948182-42b44224-16f6-4cd3-be38-29f64887c2b6.png)

which is obviously minified, and indeed clicking on any of those blue links leads to more minified code, making it extremely hard to debug.

So it would be great if sourcemaps were available for the https://synclinear.com/ deployment.  It's already Open Source, so presumably there's nothing to hide ;-)

**Comment by tedspare** [comment]
Thanks @aspiers. A PR is up [here](https://github.com/calcom/synclinear.com/pull/70) - would you be open to reviewing it?

Sidenote, big fan of Toucan.

**Comment by aspiers** [comment]
Awesome, thanks. Big fan of yours now too! 😁
