### ISSUE TITLE
Can't Sync Multiple Repos

### ISSUE THREAD

**Issue by matthawk60** [calcom/synclinear.com#71]
Have have two teams in linear and I need to sync them to two separate repos.  The UI let me do this initially.  Now it just seems to be bugged.   One repo and team doesn't sync at all and the other only syncs from linear to GitHub.  both GitHub repos throw the same error. {"success":false,"message":"GitHub webhook secret doesn't match up."}****

Any help would be appreciated.

I also tried the self hosted version.  It's not clear from the documentation what the oauth calback url should be.

**Comment by tedspare** [comment]
@matthawk60 to clarify, are you trying to sync (team A, repo A) and (team B, repo B)?

As for self-hosting, the callback URL will be your UI deployment URL, eg. `https://railway.com/matt-hawk-sync-linear/`. Would you be open to opening a PR to add this to the docs in the appropriate place?

**Comment by matthawk60** [comment]
> @matthawk60 to clarify, are you trying to sync (team A, repo A) and (team B, repo B)?
@tedspare yes that's what I was trying, however I have since manually deleted the webhooks in both linear and github so I think I"m now running into that issue.  The app won't recreate them
