### ISSUE TITLE
User mention in issue description causes infinite loop

### ISSUE THREAD

**Issue by rabah-khalek** [calcom/synclinear.com#72]
I am not sure how exactly this was triggered:
https://user-images.githubusercontent.com/32709181/221838490-53537bb6-c522-4ac2-80f4-ecf3798573fe.mov

but I started by creating the issue on linear, with tagging people, then i modified the title of the issue on linear, then modified the title of the issue on github, then I noticed this happening.

**Comment by tedspare** [comment]
Thanks @rabah-khalek - this looks very bad. Will try to replicate it to fix it.

**Comment by tedspare** [comment]
Working on a fix @rabah-khalek. Is this still happening, now with tens of thousands of lines? 😅

**Comment by tedspare** [comment]
Closed as stale / username swapping has been substantially refactored!
