### ISSUE TITLE
Allow access to selected repos only

### ISSUE THREAD

**Issue by liamwh** [calcom/synclinear.com#76]
Hi guys, thanks for making synclinear! Love the idea, however, I have closed source code which I do not want to share with linear sync, I only want to use it for my open source repos.

Can you please consider enabling this in the Github settings?

![image](https://user-images.githubusercontent.com/23312359/222902876-cdd80e6a-b2f1-4014-95d7-88bfba890f8b.png)

**Comment by tedspare** [comment]
Hi @liamwh. Thanks for the kind words. It's possible the app can function with reduced scopes: [existing issue](https://github.com/calcom/synclinear.com/issues/47#issuecomment-1399319246). Open to PRs!
