### ISSUE TITLE
Deleting sync bricks future syncs

### ISSUE THREAD

**Issue by sanderpick** [calcom/synclinear.com#82]
Here's what I did:
1. Synced a repo to a team
2. Deleted the sync
3. Noticed that deleting the sync didn't delete the GH webhook or linear webhook
4. Manually deleted the GH webhook and linear webbook
5. Tried to recreate the sync
6. The sync UI thinks that the linear webhook already exists, but it doesn't
7. Re-deployed the GH webhook, which now reports ping errors because the linear side doesn't exist

- Seems there is some stale data in the sync backend that isn't getting cleaned up when you delete via the synclinear UI. 
- I think it also makes sense to clean up the webhooks when you delete a sync

**Comment by sanderpick** [comment]
I tried to hack around the issue by creating a new linear team and syncing that to my repo (after deleting the GH webhook). Synclinear deployed two new webbooks, but the ping from GH fails:

<img width="814" alt="Screenshot 2023-03-13 at 7 54 28 AM" src="https://user-images.githubusercontent.com/361000/224740935-fac21381-17f0-4047-b79b-f385e0c8a6ae.png">

I suspect there is a dangling entry in the database for my repo. Any chance you can manually delete it? This is the repo: https://github.com/tablelandnetwork/evm-tableland. 

And... thank you for the great free service!

**Comment by tedspare** [comment]
Thanks @sanderpick - you zeroed in on the dangling entry problem. The UI _thinking_ there's a webhook comes from a DB check, not a GH webhook API check (design flaw on my part). Would you be open to trying a PR to either/both:
1. Cascade GH repo deletions from associated sync deletions using [Prisma's cascade syntax](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions#example-usage)
2. Check for an existing webhook in the UI?

Would be much appreciated but otherwise I'll get to it eventually.

**Comment by sanderpick** [comment]
Makes sense. I'm still evaluating if this sync tool will work for my team. I have seen a couple other issues (one is around possible expiring oauth tokens that brick a sync — i'll open an issue). If I can get around those, I'm very much game to contribute here!

**Comment by kharann** [comment]
Hi! I think i'm facing the same problem. I accidently moved a label from Team to Workspace, which briked the sync initially. Then I deleted the webhooks and label in an attempt to setup a hook again. For some reason, the redeploy didn't work on github, where I'm facing the same problem as described. I also cannot redeploy the webhook to linear

**Comment by kharann** [comment]
I think this might be solved by also updating the webhook secret in 

https://github.com/calcom/synclinear.com/blob/06f4b612c29d987bbe0b4b01f8221787cea93688/pages/api/github/save.ts#L21

I might make a PR for that later

**Comment by tedspare** [comment]
Closed by #93
