### ISSUE TITLE
Unknown label ID error corresponds with broken sync

### ISSUE THREAD

**Issue by geekflyer** [calcom/synclinear.com#84]
We noticed that for some issues the sync is broken.
The webhook receives this error message on the `issues.labeled` event:
```
{"success":false,"message":"Entity not found - labelIds contained an entry that could not be found."}
```

Here's an example issue which somehow triggers this response:
https://github.com/aptos-labs/aptos-core/issues/79

**Comment by geekflyer** [comment]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/1221897/224858602-5eb0a0fd-5aa8-41ee-ab3e-954e4efdf0a0.png">

**Comment by tedspare** [comment]
Hey @geekflyer - are you still using the app? If so, would you be open to re-syncing to see if that fixes it? We fixed some pieces of the onboarding flow today that should fix this.
