### ISSUE TITLE
Cannot read "id" of undefined

### ISSUE THREAD

**Issue by jendcio** [calcom/synclinear.com#94]
I went through the steps to set this up and can create issues in linear with the `Public` label that are sent to github but when an issue in github is created it's not sending to Linear.

After implementation, we noticed that the webhook was not showing on the github side. We manually tried to set one up but I'm assuming we don't have the correct secret. We see recent delivery info now if we tag an issue with the `linear` label but each delivery has a 500 with a response of: 

```
Cache-Control: public, max-age=0, must-revalidate
Content-Length: 80
Content-Type: application/json; charset=utf-8
Date: Fri, 28 Apr 2023 18:42:56 GMT
Etag: &quot;ktwr6rnmyt28&quot;
Server: Vercel
Strict-Transport-Security: max-age=63072000
X-Matched-Path: /api
X-Vercel-Cache: MISS
X-Vercel-Id: iad1::iad1::zvrrt-1682707376402-4616e1e9702f

{"success":false,"message":"Cannot read properties of undefined (reading 'id')"}
```

UPDATE: I tried enabling the sync again for github and was seeing errors in the network responses. I grabbed the webhookSecret that was in the network call and put that into my manually configured webhook in Github. Even after that I'm still seeing the same issue as above.

**Comment by tedspare** [comment]
Hi @jendcio, sorry for the late response - it took me a while to think through this.

If I understand correctly, the GH webhook is working now, but the SyncLinear server fails (with a 500) to create the Linear ticket?

The `Cannot read properties of undefined (reading 'id')` tells me either the incoming `repository` or `sender` is undefined in the GitHub webhook handler. I've pushed a check for these - could you try again and let me know if that helps?

**Comment by jendcio** [comment]
Hi @tedspare we just tried this again and are no longer getting the 500 but we are getting a 404 with the message

```
{"success":false,"message":"Could not find issue's corresponding sync."}
```

This happens after adding the `linear` label to an issue in Github. I also re-confirmed that the webhook secret we have in our github setup matches the secret I get in the network response when enabling the sync. I also confirmed that sending issues from Linear to Github is still working.

**Comment by jendcio** [comment]
Just as an extra bit of info, when trying to set up the the github webhook I get a 404 response to the call to `https://synclinear.com/api/github/webhook` but the error object is empty. Which is why I was manually grabbing the webhook secret from the `https://synclinear.com/api/github/save` request

**Comment by tedspare** [comment]
Thanks for the details, @jendcio! Does your Linear team have a label titled "Public"? (Sorry for the narrowness in our logic - working on generalizing this).

Also, could you share the name of the repo? Curious if we failed to save the repo to DB.

**Comment by tedspare** [comment]
As well, does your GH webhook point to `https://synclinear.com/api`?

**Comment by tedspare** [comment]
Hey @jendcio, going to close this as (if I recall) we figured out it was a private repo issue! Always open to re-opening

**Comment by jendcio** [comment]
@tedspare do you know if the private repo issue has been resolved? I'd love to give this another shot if possible!
