### ISSUE TITLE
Redeploy Linear webhook/Broken sync from Linear to GitHub

### ISSUE THREAD

**Issue by kharann** [calcom/synclinear.com#96]
Hi!

A few weeks ago I managed to break the sync between my linear team and GitHub. I did make a recent PR which fixed the redeployment of a GitHub webhook. Luckily, the sync from GitHub to Linear seems to work. However, from linear to GitHub remains broken.

I broke it by:

1. Accidently move the Public Label from a team level to an organization label.
2. Delete the label 
3. Re create a label named "Public"
4. Delete the team sync on synclinear.com
5. Delete the webhook in Linear, and attempt to read it

Even if I deleted the webhook, I wasn't able to redeploy it. Compared to GitHub, i was able to press the deploy webhook button when I deleted it

**Comment by tedspare** [comment]
Hey @kharann, thanks for reporting this. I think it's an issue in my logic of deleting a sync:

When a sync is deleted, the Linear team remains (in case other syncs rely on this team), causing the UI to think the Linear team is still connected.

Two solutions come to mind:
1. Add a webhook to listen to webhook update/delete events (if possible) and update the DB accordingly
2. Delete the Linear team from DB when deleting a sync if it's the only sync using that team

Would you want to take this on as well?

**Comment by kharann** [comment]
> Hey @kharann, thanks for reporting this. I think it's an issue in my logic of deleting a sync:
> 
> When a sync is deleted, the Linear team remains (in case other syncs rely on this team), causing the UI to think the Linear team is still connected.
> 
> Two solutions come to mind:
> 1. Add a webhook to listen to webhook update/delete events (if possible) and update the DB accordingly
> 2. Delete the Linear team from DB when deleting a sync if it's the only sync using that team
> 
> Would you want to take this on as well?

Yeah I might look into it during this weekend

**Comment by 0xTea** [comment]
Hey guys just wanted to we have are facing a similar issue in our organisation is there any developments on  potential fix for this  ?

**Comment by kharann** [comment]
Currently gonna be on a long vacation, so if anyone else want to give it a try go ahead

**Comment by tedspare** [comment]
@kharann I noticed a dumb cause for this - the GitHub deploy button checks for an active webhook, whereas the Linear deploy button checks our own DB for the Linear team (which might have deleted its webhook).

Working on a fix
